In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

## Importing csv's

In [2]:
avengers_endgame = pd.read_csv("./cleaned/avengers_endgame.csv")
avengers = pd.read_csv("./cleaned/avengers.csv")
ragnorak = pd.read_csv("./cleaned/ragnorak.csv")
iron_man = pd.read_csv("./cleaned/iron_man.csv")
guardians2 = pd.read_csv("./cleaned/guardians2.csv")
infinity_war = pd.read_csv("./cleaned/infinity_war.csv")

## Adding a Movie Column

In [3]:
avengers_endgame["movie"] = "Avengers: Endgame"
avengers["movie"] = "The Avengers"
ragnorak["movie"] = "Thor: Ragnarok"
iron_man["movie"] = "Iron Man"
guardians2["movie"] = "Guardians of the Galaxy Vol. 2"
infinity_war["movie"] = "Avengers: Infinity War"

## Adding Author Indicators

Indicator variables (0 = False, 1 = True) for if an author contributed to the screenplay that the line is from.  These names were taken from the Wikipedia articles for these movies.  The names used are listed in the right column in the "Screenplay By"  or "Written By" row.

In [4]:
avengers_endgame["Christopher Markus"] = True
avengers_endgame["Stephen McFeely"] = True

avengers["Joss Whedon"] = True

ragnorak["Eric Pearson"] = True
ragnorak["Craig Kyle"] = True
ragnorak["Christopher Yost"] = True

iron_man["Mark Fergus"] = True
iron_man["Hawk Ostby"] = True
iron_man["Art Marcum"] = True
iron_man["Matt Holloway"] = True

guardians2["James Gunn"] = True

infinity_war["Christopher Markus"] = True
infinity_war["Stephen McFeely"] = True

## Adding a Year Column

In [5]:
avengers_endgame["year"] = 2019
avengers["year"] = 2012
ragnorak["year"] = 2017
iron_man["year"] = 2008
guardians2["year"] = 2017
infinity_war["year"] = 2018

## Specifying Duplicate Names

Some characters happen to have the same name as characters in a different movie, though they are not the same person.  This cell specifies the difference so that their lines aren't aggregated.  This won't really matter since these characters have so few lines anyway.

In [6]:
avengers_endgame['character'] = avengers_endgame['character'].replace(["JIMMY"],'AVENGERS JIMMY')
avengers_endgame['character'] = avengers_endgame['character'].replace(["KID"],'AVENGERS KID')
iron_man['character'] = iron_man['character'].replace(["JIMMY"],'IRON MAN JIMMY')
iron_man['character'] = iron_man['character'].replace(["KID"],'IRON MAN KID')

## Creating a Combined DataFrame

In [7]:
combined = pd.concat([avengers_endgame, avengers, ragnorak, iron_man, guardians2, infinity_war])

combined.fillna(False, inplace=True)

## Removing Character Name Aliases

Some characters go by different names in different movies.  Also, some characters start out as `MYSTERIOUS MAN` and be revealed to be `EGO`.  This cell fixes that by assigning the same lines to the same name.  Some of these choices are subjective.  For example, I've decided that `HULK` is a different character than `BRUCE BANNER`, and that all reporter characters are named `REPORTER`.

When adding a new movie to this dataset, **be careful** to see that the extra characters (`MAN`, `WOMAN`, `KID` etc.) are being assigned to who they actually are.  For example, in Iron Man, `MAN` is `AGENT COULSON`, but `MAN` could be somebody else in a different movie.

In [8]:
# Iron Man People
combined['character'].replace(['IRON MAN','TONY',"VOICE"],'TONY STARK', inplace=True)
combined['character'].replace(['PEPPER'],'PEPPER POTTS', inplace=True)
combined['character'].replace(["WOMAN’S VOICE"],'CHRISTINE', inplace=True)
combined['character'].replace(["GABRIEL"],'GENERAL GABRIEL', inplace=True)
combined['character'].replace(["HOGAN"],'HAPPY HOGAN', inplace=True)
combined['character'].replace(["F.R.I.D.A.Y."],'FRIDAY', inplace=True)
combined['character'].replace(["OBADIAH"],'OBADIAH STANE', inplace=True)
combined['character'].replace(["RHODEY"],'JAMES RHODES', inplace=True)

# SHIELD People
combined['character'].replace(['BARTON'],'CLINT BARTON', inplace=True)
combined['character'].replace(['COULSON', 'MAN', 'AGENT COULSON'],'PHIL COULSON', inplace=True)
combined['character'].replace(['AGENT JASPER SITWELL', 'AGENT SITWELL'],'JAPSER SITWELL', inplace=True)
combined['character'].replace(["FURY"],'NICK FURY', inplace=True)
combined['character'].replace(["NATASHA"],'NATASHA ROMANOFF', inplace=True)

# Guardians of the Galaxy People
combined['character'].replace(['QUILL'],'PETER QUILL', inplace=True)
combined['character'].replace(['MONSTROUS RAVAGER'],'TASERFACE', inplace=True)
combined['character'].replace(['MYSTERIOUS MAN'],'EGO', inplace=True)
combined['character'].replace(["ADOLESCENT GROOT"],'GROOT', inplace=True)
combined['character'].replace(["MEREDITH"],'MEREDITH QUILL', inplace=True)
combined['character'].replace(["MEMORY GAMORA"],"GAMORA", inplace=True)
combined['character'].replace(["MEMORY NEBULA"],"NEBULA", inplace=True)

# Thor People
combined['character'].replace(['SCRAPPER #142'],'VALKYRIE', inplace=True)
combined['character'].replace(['LOKIE'],'LOKI', inplace=True)

# Other People
combined['character'].replace(['BANNER','SMART HULK', 'ASTRAL BANNER'],'BRUCE BANNER', inplace=True)
combined['character'].replace(['STEVE','CAPTAIN AMERICA', 'OLD STEVE'],'STEVE ROGERS', inplace=True)
combined['character'].replace(['STRANGE', "DOCTOR STRANGE", "DR. STRANGE", "STEVEN STRANGE"],'STEPHEN STRANGE', inplace=True)
combined['character'].replace(["HOODED FIGURE", "STONEKEEPER"],'RED SKULL', inplace=True)
combined['character'].replace(["SCHOOL BUS DRIVER, STAN LEE"],'STAN LEE', inplace=True)
combined['character'].replace(["T’CHALLA", "KING T'CHALLA"],"T'CHALLA", inplace=True)
combined['character'].replace(["WANDA"],"WANDA MAXIMOFF", inplace=True)

# Extras
combined['character'].replace(["REPORTER # 1", "REPORTER #2", "REPORTER #3","TV REPORTER’S VOICE",
                                                      "MALE REPORTER"],'REPORTER', inplace=True)
combined['character'].replace(["INTERCOM VOICE", "HELICARRIER INTERCOM"],'INTERCOM', inplace=True)
combined['character'].replace(["JET PILOT", "YOUNG SHIELD PILOT", "FACELESS PILOT"],'PILOT', inplace=True)

In [9]:
unique_names = pd.DataFrame(combined["character"].value_counts())

unique_names.rename(columns={"character": "line count"}, inplace=True)
unique_names.reset_index(inplace=True)
unique_names.rename(columns={"index": "character"}, inplace=True)

unique_names["words"] = unique_names["character"].str.split(" ").str.len()
unique_names.sort_values(by=["words", "character"], inplace=True)

unique_names

                      character  line count  words
89                          ABU           5      1
99                      ADMIRAL           4      1
143                       AGENT           2      1
106                     AKIHIKO           3      1
137                       ALETA           2      1
165                   ATTENDANT           1      1
41                       AYESHA          23      1
130              BITCHING-BETTY           2      1
171                       BRAHL           1      1
111                 CHAMBERMAID           3      1
124                  CHARLIE-27           2      1
51                    CHRISTINE          17      1
93                    COLLECTOR           5      1
62                   COUNCILMAN          12      1
79                 COUNCILWOMAN           7      1
195                      CRAMER           1      1
182                       CROWD           1      1
13                         DRAX         117      1
14                          EGO         103      1
54                        EITRI          16      1
65                       FRIDAY          11      1
50                       FRIGGA          19      1
6                        GAMORA         197      1
28                  GRANDMASTER          48      1
36                        GROOT          26      1
150                    HALF-NUT           1      1
44                     HEIMDALL          22      1
25                         HELA          57      1
118                       HOGUN           3      1
29                         HULK          45      1
151                     HUSBAND           1      1
66                     INTERCOM          11      1
27                       JARVIS          50      1
158                      KHALID           1      1
32                         KORG          36      1
45                      KRAGLIN          21      1
9                          LOKI         171      1
190                  LOKI/STEVE           1      1
107                      M'BAKU           3      1
101                        M.P.           4      1
139                      MAIDEN           2      1
185                   MAINFRAME           1      1
22                       MANTIS          71      1
136                    MARTINEX           2      1
58                     NARRATOR          13      1
17                       NEBULA          88      1
188                       NOVAR           1      1
140                        OBLO           2      1
33                         ODIN          30      1
94                      OFFICER           4      1
56                        OKOYE          14      1
85                        PILOT           6      1
108                       PRATT           3      1
155                  PROPRIETOR           1      1
72                      QUINJET           9      1
156                     RAMIREZ           1      1
40                         RAZA          23      1
55                     REPORTER          15      1
98                        RETCH           4      1
5                        ROCKET         246      1
115                       RONIN           3      1
166                   SCIENTIST           1      1
152                    SCRAPPER           1      1
191                    SECURITY           1      1
46                       SELVIG          19      1
88                        SHURI           6      1
49                       SKURGE          19      1
177                     SOLDIER           1      1
68                       STAKAR          10      1
59                       SURTUR          13      1
48                     T'CHALLA          19      1
42                    TASERFACE          23      1
12                       THANOS         127      1
1                          THOR         557      1
69                        TOPAZ          10      1
90                        TULLK           5      1
164                      TYCOON           1      1
15                     VALKYRIE          97      1
34                       VISION          30      1
199                    VOLSTAGG           1      1
144                    WAITRESS           2      1
126                      WARDEN           2      1
161                        WIFE           1      1
193                       WOMAN           1      1
64                         WONG          11      1
24                       YINSEN          59      1
19                        YONDU          82      1
128                     A1 HULK           2      2
135                  A1 NATASHA           2      2
77                     A1 STEVE           8      2
84                      A1 THOR           6      2
112                     A1 TONY           3      2
63                   ACTOR LOKI          11      2
116                  ACTOR ODIN           3      2
179                   ACTOR SIF           1      2
61                   ACTOR THOR          12      2
82             ALEXANDER PIERCE           6      2
37                  ANCIENT ONE          25      2
178          ASGARDIAN CITIZENS           1      2
157               ASGARDIAN MAN           1      2
180                ASGARDIAN PA           1      2
198             ASGARDIAN WOMAN           1      2
184              AVENGERS JIMMY           1      2
189                AVENGERS KID           1      2
43                   BAD NEBULA          23      2
109                BROCK RUMLOW           3      2
3                  BRUCE BANNER         307      2
67                 BUCKY BARNES          11      2
194              CALCUTTA WOMAN           1      2
47                CAROL DANVERS          19      2
138                 CASSIE LANG           2      2
16                 CLINT BARTON          97      2
95                CORVUS GLAIVE           4      2
170                COUNCILMAN 2           1      2
125                COUSIN CARLO           2      2
181               CULL OBSIDIAN           1      2
160                DOME CONTROL           1      2
35                    EBONY MAW          26      2
123                EDWIN JARVIS           2      2
183              FEMALE CITIZEN           1      2
134            FRIGHTENED PILOT           2      2
149             GAMORA'S MOTHER           1      2
71              GENERAL GABRIEL           9      2
78               GEORGI LUCHKOV           7      2
163               GRANDPA QUILL           1      2
96                 GRIEVING MAN           4      2
91                     HANK PYM           5      2
80                  HAPPY HOGAN           7      2
97                HEAD ENGINEER           4      2
39                 HOWARD STARK          25      2
145             JABARI WARRIORS           2      2
10                 JAMES RHODES         136      2
119                 JANE FOSTER           2      2
83               JAPSER SITWELL           6      2
122                LAURA BARTON           2      2
113               LEAD SCRAPPER           3      2
110                 LILA BARTON           3      2
186             MAINTENANCE GUY           1      2
53                  MAJOR ALLEN          16      2
104                  MALE AGENT           4      2
148                MALE CITIZEN           1      2
31                   MARIA HILL          36      2
87               MEREDITH QUILL           6      2
60                 MORGAN STARK          13      2
175               MUFFLED VOICE           1      2
187              NASA SCIENTIST           1      2
8              NATASHA ROMANOFF         194      2
153                   NED LEEDS           1      2
11                    NICK FURY         131      2
21                OBADIAH STANE          73      2
196          OFFICER FITZGIBBON           1      2
174                   OLDER MAN           1      2
86                 PEGGY CARTER           6      2
7                  PEPPER POTTS         194      2
26                 PETER PARKER          55      2
2                   PETER QUILL         312      2
23                 PHIL COULSON          69      2
100             POLICE SERGEANT           4      2
74             PROXIMA MIDNIGHT           8      2
52                    RED SKULL          17      2
38                   SAM WILSON          25      2
20                   SCOTT LANG          80      2
147          SCURRILOUS RAVAGER           1      2
75               SECRETARY ROSS           8      2
57               SECURITY GUARD          13      2
133                SHIELD AGENT           2      2
173             SHIELD ENGINEER           1      2
127               SHIELD WORKER           2      2
76               SOOTHING VOICE           8      2
168             SOVEREIGN PILOT           1      2
92                     STAN LEE           5      2
18              STEPHEN STRANGE          83      2
4                  STEVE ROGERS         285      2
172                TALL RAVAGER           1      2
70                    THE OTHER          10      2
197                 THE SENATOR           1      2
0                    TONY STARK         774      2
73                      VIPER 1           8      2
81                      VIPER 2           7      2
30               WANDA MAXIMOFF          36      2
146               WEASELLY THUG           1      2
121                   YOUNG COP           2      2
103                YOUNG GAMORA           4      2
114                  YOUNG GIRL           3      2
169             A1 CLINT BARTON           1      3
141              COLLEGE GIRL 1           2      3
120              COLLEGE GIRL 2           2      3
176             DUBAI BEAUTY #1           1      3
105         FEMALE SHIELD AGENT           4      3
117             GEF THE RAVAGER           3      3
132              GERMAN OLD MAN           2      3
131               HOPE VAN DYNE           2      3
102              IRON MAN JIMMY           4      3
159                IRON MAN KID           1      3
162           OFF SCREEN WORKER           1      3
192               THOR / BANNER           1      3
167               WEIRD OLD MAN           1      3
142       CARRIER BRIDGE TECH 1           2      4
129  FEMALE CARRIER BRIDGE TECH           2      4
154         KID IN THE BACKSEAT           1      4

In [10]:
unique_names[unique_names["character"].str.contains("SHIELD", regex=True)]

               character  line count  words
133         SHIELD AGENT           2      2
173      SHIELD ENGINEER           1      2
127        SHIELD WORKER           2      2
105  FEMALE SHIELD AGENT           4      3

## Adding a Words Column

Be aware, elipses and dashes aren't guaranteed to be counted as their own word.  For example, `down...bow` from the opening scene of Avengers Endgame might be counted as 1 word.  The same thing can happen with This shouldn't happen.  This might need to be corrected when constructing models.

In [11]:
combined["words"] = combined["line"].str.split(" ").str.len()

## Exporting mcu.csv

In [12]:
column_order = ["character", "line", "movie", "year", "words", 
                "Christopher Markus", "Stephen McFeely", "Joss Whedon", "Eric Pearson", "Craig Kyle", "Christopher Yost",
               "Mark Fergus", "Hawk Ostby", "Art Marcum", "Matt Holloway", "James Gunn"]

combined = combined[column_order]
#combined.astype('int32', copy=False)

combined.to_csv("./mcu.csv")

combined.head()

,character,line,movie,year,words,Christopher Markus,Stephen McFeely,Joss Whedon,Eric Pearson,Craig Kyle,Christopher Yost,Mark Fergus,Hawk Ostby,Art Marcum,Matt Holloway,James Gunn
0,CLINT BARTON,"Okay, you see where you’re going? Let’s work on how to get there.",Avengers: Endgame,2019,13,True,True,False,False,False,False,False,False,False,False,False
1,CLINT BARTON,"Okay, good...tip down...bow arm out...three fingers-",Avengers: Endgame,2019,7,True,True,False,False,False,False,False,False,False,False,False
2,LILA BARTON,Why three?,Avengers: Endgame,2019,2,True,True,False,False,False,False,False,False,False,False,False
3,CLINT BARTON,‘Cause two’s not enough and four’s too much-,Avengers: Endgame,2019,8,True,True,False,False,False,False,False,False,False,False,False
4,LAURA BARTON,"You guys want mustard or mayo, or both?",Avengers: Endgame,2019,8,True,True,False,False,False,False,False,False,False,False,False

## Movie Metadata Table

In [13]:
movies = pd.DataFrame()

movies = movies.append(pd.Series({"movie": "Avengers: Endgame", "year": 2019, "is transcript": False, "lines": avengers_endgame.shape[0], "url": "https://www.scriptslug.com/assets/uploads/scripts/avengers-endgame-2019.pdf"}), ignore_index=True)
movies = movies.append(pd.Series({"movie": "The Avengers", "year": 2012, "is transcript": False, "lines": avengers.shape[0], "url": "https://www.scriptslug.com/assets/uploads/scripts/the-avengers-2012.pdf"}), ignore_index=True)
movies = movies.append(pd.Series({"movie": "Thor: Ragnorak", "year": 2017, "is transcript": False, "lines": ragnorak.shape[0], "url" : "https://www.scriptslug.com/assets/uploads/scripts/thor-ragnorak-2017.pdf"}), ignore_index=True)
movies = movies.append(pd.Series({"movie": "Iron Man", "year": 2008, "is transcript": False, "lines": iron_man.shape[0], "url": "https://www.scriptslug.com/assets/uploads/scripts/iron-man-2008.pdf"}), ignore_index=True)
movies = movies.append(pd.Series({"movie": "Guardians of the Galaxy Vol. 2", "year": 2017, "is transcript": False, "lines": guardians2.shape[0], "url" : "https://www.scriptslug.com/assets/uploads/scripts/guardians-of-the-galaxy-vol-2-2017.pdf"}), ignore_index=True)
movies = movies.append(pd.Series({"movie": "Avengers: Infinity War", "year": 2018, "is transcript": True, "lines": infinity_war.shape[0], "url" : "https://transcripts.fandom.com/wiki/Avengers:_Infinity_War"}), ignore_index=True)

movies.set_index('movie', inplace=True)
movies["is transcript"] = movies['is transcript'].astype('boolean', copy=False)
movies["lines"] = movies['lines'].astype('int64', copy=False)
movies["year"] = movies['year'].astype('int64', copy=False)

movies.sort_values(by="year", inplace=True)

movies.to_csv("./movies.csv")

movies

,is transcript,lines,url,year
movie,,,,
Iron Man,False,834,https://www.scriptslug.com/assets/uploads/scripts/iron-man-2008.pdf,2008
The Avengers,False,1027,https://www.scriptslug.com/assets/uploads/scripts/the-avengers-2012.pdf,2012
Thor: Ragnorak,False,961,https://www.scriptslug.com/assets/uploads/scripts/thor-ragnorak-2017.pdf,2017
Guardians of the Galaxy Vol. 2,False,993,https://www.scriptslug.com/assets/uploads/scripts/guardians-of-the-galaxy-vol-2-2017.pdf,2017
Avengers: Infinity War,True,990,https://transcripts.fandom.com/wiki/Avengers:_Infinity_War,2018
Avengers: Endgame,False,1229,https://www.scriptslug.com/assets/uploads/scripts/avengers-endgame-2019.pdf,2019